apiVersion: apiserver.config.k8s.io/v1beta1
kind: AuthenticationConfiguration
jwt:
  - issuer:
      url: https://hydra.enkinineveh.space/
      audiences:
        - kube-cluster-1
      audienceMatchPolicy: MatchAny
    claimMappings:
      username:
        expression: "claims.sub"
      groups:
        expression: "claims.groups"
      uid:
        expression: "claims.uid"
      extra:
        - key: "example.com/tenant"
          expression: "claims.tenant"
    userValidationRules:
      - expression: "!user.username.startsWith('system:')"
        message: "username cannot use reserved system: prefix"
