apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-auth
data:
  client_id: {{ .Values.secret.oauth2.client_credentials.client_id | b64enc }}
  client_secret: {{ .Values.secret.oauth2.client_credentials.client_secret  | b64enc }}